steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/connekt-camp-api:$SHORT_SHA", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/connekt-camp-api:$SHORT_SHA"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "connekt-camp-api",
        "--image=gcr.io/$PROJECT_ID/connekt-camp-api:$SHORT_SHA",
        "--region=asia-south1",
        "--allow-unauthenticated",
        "--set-secrets",
        "MONGO_DB_URI=connekt-camp-db-uri:latest,FIREBASE_SERVICE_ACCOUNT=connekt-camp-service-account:latest",
      ]
options:
  logging: CLOUD_LOGGING_ONLY
